sudo: required
services:
    - docker
    
before_install:
    - docker build -t crosscutsaw/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true crosscutsaw/docker-react npm run test -- --coverage
    
language: generic